create extension if not exists pgcrypto;

create or replace function public.current_clinic_id()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('app.current_clinic_id', true), '')::uuid;
$$;

create table if not exists clinics (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  subdomain text unique not null,
  address text,
  phone text,
  subscription_tier text not null check (subscription_tier in ('free', 'pro', 'enterprise')),
  created_at timestamptz not null default now()
);

create table if not exists staff (
  id uuid primary key default gen_random_uuid(),
  clinic_id uuid not null references clinics(id) on delete cascade,
  role text not null check (role in ('doctor', 'receptionist', 'admin')),
  full_name text not null,
  specialty text,
  auth_user_id uuid unique references auth.users(id)
);

create table if not exists patients (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id),
  full_name text not null,
  phone text unique not null,
  date_of_birth date,
  national_id text
);

create table if not exists doctor_availability (
  id uuid primary key default gen_random_uuid(),
  staff_id uuid not null references staff(id) on delete cascade,
  day_of_week int not null check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  slot_duration_minutes int not null default 30 check (slot_duration_minutes > 0)
);

create table if not exists appointments (
  id uuid primary key default gen_random_uuid(),
  clinic_id uuid not null references clinics(id) on delete cascade,
  patient_id uuid not null references patients(id) on delete cascade,
  staff_id uuid not null references staff(id) on delete cascade,
  scheduled_at timestamptz not null,
  duration_minutes int not null default 30 check (duration_minutes > 0),
  status text not null check (status in ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')),
  reason text,
  created_at timestamptz not null default now(),
  cancelled_reason text
);

create table if not exists medical_records (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references patients(id) on delete cascade,
  appointment_id uuid not null references appointments(id) on delete cascade,
  notes text,
  attachments jsonb not null default '[]'::jsonb,
  created_by uuid references staff(id),
  created_at timestamptz not null default now()
);

create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references appointments(id) on delete cascade,
  amount_iqd numeric not null check (amount_iqd >= 0),
  provider text not null check (provider in ('zaincash', 'qicard', 'cash')),
  status text not null check (status in ('pending', 'paid', 'failed', 'refunded')),
  transaction_ref text,
  created_at timestamptz not null default now()
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  clinic_id uuid,
  actor_user_id uuid,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists unique_active_slot
  on appointments(staff_id, scheduled_at)
  where status <> 'cancelled';

create index if not exists idx_staff_clinic_id on staff(clinic_id);
create index if not exists idx_appointments_clinic_id on appointments(clinic_id);
create index if not exists idx_appointments_patient_id on appointments(patient_id);
create index if not exists idx_appointments_staff_id on appointments(staff_id);
create index if not exists idx_medical_records_patient_id on medical_records(patient_id);
create index if not exists idx_payments_appointment_id on payments(appointment_id);
create index if not exists idx_audit_logs_clinic_id_created_at on audit_logs(clinic_id, created_at desc);

alter table clinics enable row level security;
alter table staff enable row level security;
alter table patients enable row level security;
alter table doctor_availability enable row level security;
alter table appointments enable row level security;
alter table medical_records enable row level security;
alter table payments enable row level security;
alter table audit_logs enable row level security;

create policy if not exists clinics_read_own on clinics
for select to authenticated
using (id = public.current_clinic_id());

create policy if not exists staff_read_own_clinic on staff
for select to authenticated
using (clinic_id = public.current_clinic_id());

create policy if not exists staff_manage_own_clinic on staff
for all to authenticated
using (clinic_id = public.current_clinic_id())
with check (clinic_id = public.current_clinic_id());

create policy if not exists patient_self_access on patients
for select to authenticated
using (auth_user_id = auth.uid());

create policy if not exists patient_self_update on patients
for update to authenticated
using (auth_user_id = auth.uid())
with check (auth_user_id = auth.uid());

create policy if not exists doctor_availability_by_clinic on doctor_availability
for all to authenticated
using (
  exists (
    select 1 from staff s
    where s.id = doctor_availability.staff_id
      and s.clinic_id = public.current_clinic_id()
  )
)
with check (
  exists (
    select 1 from staff s
    where s.id = doctor_availability.staff_id
      and s.clinic_id = public.current_clinic_id()
  )
);

create policy if not exists appointments_clinic_staff_access on appointments
for all to authenticated
using (clinic_id = public.current_clinic_id())
with check (clinic_id = public.current_clinic_id());

create policy if not exists appointments_patient_access on appointments
for select to authenticated
using (
  exists (
    select 1 from patients p
    where p.id = appointments.patient_id
      and p.auth_user_id = auth.uid()
  )
);

create policy if not exists medical_records_clinic_staff_access on medical_records
for all to authenticated
using (
  exists (
    select 1
    from appointments a
    where a.id = medical_records.appointment_id
      and a.clinic_id = public.current_clinic_id()
  )
)
with check (
  exists (
    select 1
    from appointments a
    where a.id = medical_records.appointment_id
      and a.clinic_id = public.current_clinic_id()
  )
);

create policy if not exists medical_records_patient_access on medical_records
for select to authenticated
using (
  exists (
    select 1 from patients p
    where p.id = medical_records.patient_id
      and p.auth_user_id = auth.uid()
  )
);

create policy if not exists payments_clinic_staff_access on payments
for all to authenticated
using (
  exists (
    select 1
    from appointments a
    where a.id = payments.appointment_id
      and a.clinic_id = public.current_clinic_id()
  )
)
with check (
  exists (
    select 1
    from appointments a
    where a.id = payments.appointment_id
      and a.clinic_id = public.current_clinic_id()
  )
);

create policy if not exists audit_logs_clinic_access on audit_logs
for select to authenticated
using (clinic_id = public.current_clinic_id());

create or replace function public.log_audit_event(
  p_clinic_id uuid,
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
as $$
begin
  insert into audit_logs (clinic_id, actor_user_id, action, entity_type, entity_id, metadata)
  values (p_clinic_id, auth.uid(), p_action, p_entity_type, p_entity_id, coalesce(p_metadata, '{}'::jsonb));
end;
$$;

create or replace function public.book_appointment(
  p_staff_id uuid,
  p_patient_id uuid,
  p_scheduled_at timestamptz,
  p_reason text default null,
  p_duration_minutes int default 30
)
returns appointments
language plpgsql
security definer
as $$
declare
  v_clinic_id uuid;
  v_existing appointments;
  v_appointment appointments;
begin
  select clinic_id
    into v_clinic_id
  from staff
  where id = p_staff_id
    and role = 'doctor';

  if v_clinic_id is null then
    raise exception 'Doctor not found';
  end if;

  select *
    into v_existing
  from appointments
  where staff_id = p_staff_id
    and scheduled_at = p_scheduled_at
    and status <> 'cancelled'
  for update;

  if found then
    raise exception 'Slot already booked';
  end if;

  insert into appointments (
    clinic_id,
    patient_id,
    staff_id,
    scheduled_at,
    duration_minutes,
    status,
    reason
  )
  values (
    v_clinic_id,
    p_patient_id,
    p_staff_id,
    p_scheduled_at,
    p_duration_minutes,
    'pending',
    p_reason
  )
  returning * into v_appointment;

  perform public.log_audit_event(
    v_clinic_id,
    'appointment.created',
    'appointments',
    v_appointment.id::text,
    jsonb_build_object('patient_id', p_patient_id, 'staff_id', p_staff_id)
  );

  return v_appointment;
end;
$$;
